### PR TITLE
Add HL as supported target

### LINKED ISSUE #47: Interferes with HashLink export
Gives "FATAL ERROR : Failed to load library ssl.hdll"
I'm preeeetty sure it's something to do with http or something like that, I don't know too many details, just heard that could be an issue

### PR DESCRIPTION
**Pull request by MSGhero**
Closes #47 

Testing on HL from Heaps, there's nothing gamebreaking about this library. Functionality needs to be added in a couple places, but that shouldn't cause an error. I'll make a separate issue for functionality.

### CODE REVIEW

**Comment by Cheemsandfriends** [comment]
Maybe it should be easy to add
` If (desktop || Web)` ?

**Comment by Cheemsandfriends** [comment]
I think it's kinda not useful since HL is a desktop thing...
Or maybe not idk

**Comment by Geokureli** [comment]
Cheem, I do want NGio to work on desktop, and while hl is often used only for debugging, apparently some companies build distributables from hl, so I should just make apis like this available for hl.

MSG, when I said "PR it" I just assumed you weren't seeing the passport because of your test setup, but i was wrong. we should fix #54 and include that in this merge

**Comment by Cheemsandfriends** [comment]
> Cheem, I do want NGio to work on desktop, and while hl is often used only for debugging, apparently some companies build distributables from hl, so I should just make apis like this available for hl.
> 
> MSG, when I said "PR it" I just assumed you weren't seeing the passport because of your test setup, but i was wrong. we should fix #54 and include that in this merge

What I meant of that it isn't useful, I meant because I remember when I tried to first debug, I had discord RPC and I couldn't debug cos it was `#if desktop`
So I thought that desktop is included in HL,
(But Idk if hl works on Web too) so I thought maybe looking for 
`!if ( desktop || web)
{
 throw "//error lol"
}`

**Comment by Geokureli** [comment]
@MSGhero I'm testing this on mac right now, but how does this sound?

**Comment by MSGhero** [comment]
Yeah looks good to me

**Pull request merged**
