### PR TITLE
Fixes for 2.0

### PR DESCRIPTION
**Pull request by MSGhero**
I'm leaving this as a draft until I get things fully working on my current project. Feel free to update `master` in the meantime, I'll just leave it draft if so.

### CODE REVIEW

**Comment by MSGhero** [comment]
I'm getting a hard thread exception on Heaps HL `"Can't cast (void (dynamic,virtual<className:String,customParams:hl.types.ArrayDyn,fileName:String,lineNumber:i32,methodName:String>)) to (void (String))"`, so I'm gonna stop for now and check the diff

**Comment by MSGhero** [comment]
All working now on HL

**Comment by Geokureli** [comment]
Thanks for this! I'm on vacation right now, ill try to take a look at this soon.

**Comment by Geokureli** [comment]
When i tried the openfl sample project with HL on your branch I got this error after I clicked the start button:
> SIGNAL 11
sys.ssl.$Certificate.loadDefaults(/usr/local/lib/haxe/std/hl/_std/sys/ssl/Certificate.hx:54)
sys.ssl.Socket.init(/usr/local/lib/haxe/std/hl/_std/sys/ssl/Socket.hx:128)
sys.net.$Socket.__constructor__(/usr/local/lib/haxe/std/hl/_std/sys/net/Socket.hx:130)
sys.ssl.$Socket.__constructor__(/usr/local/lib/haxe/std/hl/_std/sys/ssl/Socket.hx:102)
sys.Http.customRequest(/usr/local/lib/haxe/std/sys/Http.hx:108)
sys.Http.request(/usr/local/lib/haxe/std/sys/Http.hx:68)
io.newgrounds.utils.$AsyncHttp.sendSync(io/newgrounds/utils/AsyncHttp.hx:95)
io.newgrounds.utils.$AsyncHttp.sendThreaded(io/newgrounds/utils/AsyncHttp.hx:222)
sys.thread._Thread.$HaxeThread.~create.0(/usr/local/lib/haxe/std/hl/_std/sys/thread/Thread.hx:131)

this works fine on my master branch

**Comment by Geokureli** [comment]
I changed loaderData's `(any:Any, ?pos:PosInfos)->Void` `(msg:String, ?pos:PosInfos)->Void` and now I'm just getting `SIGNAL 11`

are you using latest lime/openfl/swf? are you testing on a personal project?

when i try on the test project with -Dsimple I get this error:
> hl(72318,0x700009559000) malloc: Incorrect checksum for freed object 0x7fdba9086c78: probably modified after being freed.
Corrupt value: 0x3
hl(72318,0x700009559000) malloc: *** set a breakpoint in malloc_error_break to debug

also, I've only got my mac until Saturday

**Comment by MSGhero** [comment]
I'm using heaps HL, no openfl or lime at all.

If you're getting bytecode level errors for code that runs fine for me, and I get compiler errors for code that works for you, then I have to assume openfl is doing something weird.

If master works completely fine for you, I guess we have to ifdef these changes in some way? I don't get why even `Timer` doesn't error for you since that is just a normal int/float type check.

**Comment by Geokureli** [comment]
Screen Shot 2022-09-15 at 3 27 25 PM

**Comment by MSGhero** [comment]
That commit breaks in heaps HL, so it's not something I want to add to the PR without an ifdef

**Comment by Geokureli** [comment]
I tried testing HL on my wndows device, got the following error:
> ../lib/Source/io/newgrounds/Call.hx:215: [Newgrounds API] :: Error: SSL - No CA Chain is set, but required to operate

All of the threads I can find regarding this seem out of date and unrelated
https://github.com/HaxeFoundation/hxcpp/issues/570
https://github.com/yupswing/akifox-asynchttp/issues/43

**Comment by Geokureli** [comment]
I was under the impression that the signal 11 error and malloc errors were introduced by these changes, however when I change logVerbose to `(String, ?PosInfos)->Void`, I get them in master as well. I'll just make a separate issue for that

**Comment by Geokureli** [comment]
Thanks again for this! I was worried these changes were too drastic and no one would want to upgrade to 2.0.0, so this gives me confidence.

That said, I still think I'm going to build a version 1.4.0, which is just 1.3.0 with the new external app_id feature, just in case people need that feature but don't want to migrate an entire project

**Pull request merged**
